/**
 * TASK 02 runtime message contract — MV3 extension foundation only.
 *
 * This is NOT a domain/capture message contract. Domain messages
 * (capture, NormalizedDocument, AgentPackage) are defined in later stages.
 *
 * Every message is a discriminated union on `type` and carries a `requestId`
 * correlation ID (generated by the sender with crypto.randomUUID()).
 * `requestId` is a runtime correlation ID, NOT a future captureId.
 *
 * Messages crossing extension contexts are `unknown` first; use the exported
 * type guards before trusting any payload.
 */

export const RUNTIME_CHECK_REQUEST = "runtime.check.request" as const;
export const RUNTIME_CHECK_SUCCESS = "runtime.check.success" as const;
export const RUNTIME_CHECK_FAILURE = "runtime.check.failure" as const;
export const CONTENT_RUNTIME_CHECK_REQUEST = "content.runtimeCheck.request" as const;
export const CONTENT_RUNTIME_CHECK_SUCCESS = "content.runtimeCheck.success" as const;
export const CONTENT_RUNTIME_CHECK_FAILURE = "content.runtimeCheck.failure" as const;

/** Side Panel → Service Worker: request a foundation runtime check. */
export interface RuntimeCheckRequest {
  type: typeof RUNTIME_CHECK_REQUEST;
  requestId: string;
}

/** Service Worker → Side Panel: the runtime round-trip succeeded. */
export interface RuntimeCheckSuccess {
  type: typeof RUNTIME_CHECK_SUCCESS;
  requestId: string;
}

/** Service Worker → Side Panel: sanitized, user-readable failure. */
export interface RuntimeCheckFailure {
  type: typeof RUNTIME_CHECK_FAILURE;
  requestId: string;
  message: string;
}

/** Service Worker → Content Script: prove the script executes in the page. */
export interface ContentRuntimeCheckRequest {
  type: typeof CONTENT_RUNTIME_CHECK_REQUEST;
  requestId: string;
}

/** Content Script → Service Worker: script executed successfully. */
export interface ContentRuntimeCheckSuccess {
  type: typeof CONTENT_RUNTIME_CHECK_SUCCESS;
  requestId: string;
}

/** Content Script → Service Worker: script executed but check failed. */
export interface ContentRuntimeCheckFailure {
  type: typeof CONTENT_RUNTIME_CHECK_FAILURE;
  requestId: string;
  message: string;
}

export type RuntimeCheckMessage =
  | RuntimeCheckRequest
  | RuntimeCheckSuccess
  | RuntimeCheckFailure;

export type ContentRuntimeCheckMessage =
  | ContentRuntimeCheckRequest
  | ContentRuntimeCheckSuccess
  | ContentRuntimeCheckFailure;

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function hasOnlyKeys(value: Record<string, unknown>, keys: readonly string[]): boolean {
  const allowed = new Set(keys);
  return Object.keys(value).every((key) => allowed.has(key));
}

function isNonEmptyString(value: unknown): value is string {
  return typeof value === "string" && value.length > 0;
}

export function isRuntimeCheckRequest(value: unknown): value is RuntimeCheckRequest {
  return (
    isRecord(value) &&
    value.type === RUNTIME_CHECK_REQUEST &&
    isNonEmptyString(value.requestId) &&
    hasOnlyKeys(value, ["type", "requestId"])
  );
}

export function isRuntimeCheckSuccess(value: unknown): value is RuntimeCheckSuccess {
  return (
    isRecord(value) &&
    value.type === RUNTIME_CHECK_SUCCESS &&
    isNonEmptyString(value.requestId) &&
    hasOnlyKeys(value, ["type", "requestId"])
  );
}

export function isRuntimeCheckFailure(value: unknown): value is RuntimeCheckFailure {
  return (
    isRecord(value) &&
    value.type === RUNTIME_CHECK_FAILURE &&
    isNonEmptyString(value.requestId) &&
    isNonEmptyString(value.message) &&
    hasOnlyKeys(value, ["type", "requestId", "message"])
  );
}

export function isContentRuntimeCheckRequest(
  value: unknown,
): value is ContentRuntimeCheckRequest {
  return (
    isRecord(value) &&
    value.type === CONTENT_RUNTIME_CHECK_REQUEST &&
    isNonEmptyString(value.requestId) &&
    hasOnlyKeys(value, ["type", "requestId"])
  );
}

export function isContentRuntimeCheckSuccess(
  value: unknown,
): value is ContentRuntimeCheckSuccess {
  return (
    isRecord(value) &&
    value.type === CONTENT_RUNTIME_CHECK_SUCCESS &&
    isNonEmptyString(value.requestId) &&
    hasOnlyKeys(value, ["type", "requestId"])
  );
}

export function isContentRuntimeCheckFailure(
  value: unknown,
): value is ContentRuntimeCheckFailure {
  return (
    isRecord(value) &&
    value.type === CONTENT_RUNTIME_CHECK_FAILURE &&
    isNonEmptyString(value.requestId) &&
    isNonEmptyString(value.message) &&
    hasOnlyKeys(value, ["type", "requestId", "message"])
  );
}
